packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
