import { expect, test } from "bun:test";
import { pieceIds } from "@/cube/helpers/pieceIds";
import { createPieceScheme } from "@/cube/initializers/createPieceScheme";
import { rotatePiece } from "@/cube/internal/rotatePiece";
import { mockPieceScheme } from "@/cube/test/mockPieceScheme";
import { Faces } from "@/cube/types/Faces";
import { PieceType } from "@/cube/types/Piece";
import type { PieceScheme } from "@/cube/types/PieceScheme";
import { FundamentalRotations } from "@/cube/types/Rotations";

const c = createPieceScheme;
const m = mockPieceScheme;
const F = Faces;

test.each([
	{
		id: "U-1-C",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.BLU),
		expectedScheme: m({ U: F.U, R: F.B, B: F.L }),
	},
	{
		id: "U-2-C",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.BRU),
		expectedScheme: m({ U: F.U, R: F.B, F: F.R }),
	},
	{
		id: "U-3-C",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ U: F.U, L: F.F, F: F.R }),
	},
	{
		id: "U-4-C",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.FLU),
		expectedScheme: m({ U: F.U, L: F.F, B: F.L }),
	},
	{
		id: "U-5-E",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.BU),
		expectedScheme: m({ U: F.U, R: F.B }),
	},
	{
		id: "U-6-E",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ U: F.U, F: F.R }),
	},
	{
		id: "U-7-E",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ U: F.U, L: F.F }),
	},
	{
		id: "U-8-E",
		rotation: FundamentalRotations.U,
		scheme: c(pieceIds.LU),
		expectedScheme: m({ U: F.U, B: F.L }),
	},
	{
		id: "U-9-C",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.BLU),
		expectedScheme: m({ U: F.U, L: F.B, F: F.L }),
	},
	{
		id: "U-10-C",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.BRU),
		expectedScheme: m({ U: F.U, L: F.B, B: F.R }),
	},
	{
		id: "U-11-C",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ U: F.U, R: F.F, B: F.R }),
	},
	{
		id: "U-12-C",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.FLU),
		expectedScheme: m({ U: F.U, R: F.F, F: F.L }),
	},
	{
		id: "U-13-E",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.BU),
		expectedScheme: m({ U: F.U, L: F.B }),
	},
	{
		id: "U-14-E",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ U: F.U, B: F.R }),
	},
	{
		id: "U-15-E",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ U: F.U, R: F.F }),
	},
	{
		id: "U-16-E",
		rotation: FundamentalRotations.U_,
		scheme: c(pieceIds.LU),
		expectedScheme: m({ U: F.U, F: F.L }),
	},
	{
		id: "D-1-C",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.BDL),
		expectedScheme: m({ D: F.D, L: F.B, F: F.L }),
	},
	{
		id: "D-2-C",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.BDR),
		expectedScheme: m({ D: F.D, L: F.B, B: F.R }),
	},
	{
		id: "D-3-C",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ D: F.D, R: F.F, B: F.R }),
	},
	{
		id: "D-4-C",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.DFL),
		expectedScheme: m({ D: F.D, R: F.F, F: F.L }),
	},
	{
		id: "D-5-E",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.BD),
		expectedScheme: m({ D: F.D, L: F.B }),
	},
	{
		id: "D-6-E",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ D: F.D, B: F.R }),
	},
	{
		id: "D-7-E",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ D: F.D, R: F.F }),
	},
	{
		id: "D-8-E",
		rotation: FundamentalRotations.D,
		scheme: c(pieceIds.DL),
		expectedScheme: m({ D: F.D, F: F.L }),
	},
	{
		id: "D-9-C",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.BDL),
		expectedScheme: m({ D: F.D, R: F.B, B: F.L }),
	},
	{
		id: "D-10-C",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.BDR),
		expectedScheme: m({ D: F.D, R: F.B, F: F.R }),
	},
	{
		id: "D-11-C",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ D: F.D, L: F.F, F: F.R }),
	},
	{
		id: "D-12-C",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.DFL),
		expectedScheme: m({ D: F.D, L: F.F, B: F.L }),
	},
	{
		id: "D-13-E",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.BD),
		expectedScheme: m({ D: F.D, R: F.B }),
	},
	{
		id: "D-14-E",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ D: F.D, F: F.R }),
	},
	{
		id: "D-15-E",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ D: F.D, L: F.F }),
	},
	{
		id: "D-16-E",
		rotation: FundamentalRotations.D_,
		scheme: c(pieceIds.DL),
		expectedScheme: m({ D: F.D, B: F.L }),
	},
	{
		id: "R-1-C",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.BRU),
		expectedScheme: m({ R: F.R, B: F.U, D: F.B }),
	},
	{
		id: "R-2-C",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.BDR),
		expectedScheme: m({ R: F.R, D: F.B, F: F.D }),
	},
	{
		id: "R-3-C",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ R: F.R, F: F.D, U: F.F }),
	},
	{
		id: "R-4-C",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ R: F.R, B: F.U, U: F.F }),
	},
	{
		id: "R-5-E",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ R: F.R, B: F.U }),
	},
	{
		id: "R-6-E",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.BR),
		expectedScheme: m({ R: F.R, D: F.B }),
	},
	{
		id: "R-7-E",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ R: F.R, F: F.D }),
	},
	{
		id: "R-8-E",
		rotation: FundamentalRotations.R,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ R: F.R, U: F.F }),
	},
	{
		id: "R-9-C",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.BRU),
		expectedScheme: m({ R: F.R, U: F.B, F: F.U }),
	},
	{
		id: "R-10-C",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.BDR),
		expectedScheme: m({ R: F.R, U: F.B, B: F.D }),
	},
	{
		id: "R-11-C",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ R: F.R, B: F.D, D: F.F }),
	},
	{
		id: "R-12-C",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ R: F.R, F: F.U, D: F.F }),
	},
	{
		id: "R-13-E",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ R: F.R, F: F.U }),
	},
	{
		id: "R-14-E",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.BR),
		expectedScheme: m({ R: F.R, U: F.B }),
	},
	{
		id: "R-15-E",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ R: F.R, B: F.D }),
	},
	{
		id: "R-16-E",
		rotation: FundamentalRotations.R_,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ R: F.R, D: F.F }),
	},
	{
		id: "L-1-C",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.BRU),
		expectedScheme: m({ R: F.R, U: F.B, F: F.U }),
	},
	{
		id: "L-2-C",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.BDR),
		expectedScheme: m({ R: F.R, U: F.B, B: F.D }),
	},
	{
		id: "L-3-C",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ R: F.R, B: F.D, D: F.F }),
	},
	{
		id: "L-4-C",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ R: F.R, F: F.U, D: F.F }),
	},
	{
		id: "L-5-E",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ R: F.R, F: F.U }),
	},
	{
		id: "L-6-E",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.BR),
		expectedScheme: m({ R: F.R, U: F.B }),
	},
	{
		id: "L-7-E",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ R: F.R, B: F.D }),
	},
	{
		id: "L-8-E",
		rotation: FundamentalRotations.L,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ R: F.R, D: F.F }),
	},
	{
		id: "L-9-C",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.BRU),
		expectedScheme: m({ R: F.R, B: F.U, D: F.B }),
	},
	{
		id: "L-10-C",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.BDR),
		expectedScheme: m({ R: F.R, D: F.B, F: F.D }),
	},
	{
		id: "L-11-C",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ R: F.R, F: F.D, U: F.F }),
	},
	{
		id: "L-12-C",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ R: F.R, B: F.U, U: F.F }),
	},
	{
		id: "L-13-E",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ R: F.R, B: F.U }),
	},
	{
		id: "L-14-E",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.BR),
		expectedScheme: m({ R: F.R, D: F.B }),
	},
	{
		id: "L-15-E",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ R: F.R, F: F.D }),
	},
	{
		id: "L-16-E",
		rotation: FundamentalRotations.L_,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ R: F.R, U: F.F }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.FLU),
		expectedScheme: m({ F: F.F, U: F.L, R: F.U }),
	},
	{
		id: "F-2-C",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ F: F.F, R: F.U, D: F.R }),
	},
	{
		id: "F-3-C",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ F: F.F, L: F.D, D: F.R }),
	},
	{
		id: "F-4-C",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.DFL),
		expectedScheme: m({ F: F.F, L: F.D, U: F.L }),
	},
	{
		id: "F-5-E",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ F: F.F, R: F.U }),
	},
	{
		id: "F-6-E",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ F: F.F, D: F.R }),
	},
	{
		id: "F-7-E",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ F: F.F, L: F.D }),
	},
	{
		id: "F-8-E",
		rotation: FundamentalRotations.F,
		scheme: c(pieceIds.FL),
		expectedScheme: m({ F: F.F, U: F.L }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.FLU),
		expectedScheme: m({ F: F.F, L: F.U, D: F.L }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ F: F.F, L: F.U, U: F.R }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ F: F.F, R: F.D, U: F.R }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.DFL),
		expectedScheme: m({ F: F.F, R: F.D, D: F.L }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ F: F.F, L: F.U }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ F: F.F, U: F.R }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ F: F.F, R: F.D }),
	},
	{
		id: "F-1-C",
		rotation: FundamentalRotations.F_,
		scheme: c(pieceIds.FL),
		expectedScheme: m({ F: F.F, D: F.L }),
	},
	{
		id: "B-1-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.FLU),
		expectedScheme: m({ F: F.F, L: F.U, D: F.L }),
	},
	{
		id: "B-2-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ F: F.F, L: F.U, U: F.R }),
	},
	{
		id: "B-3-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ F: F.F, R: F.D, U: F.R }),
	},
	{
		id: "B-4-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.DFL),
		expectedScheme: m({ F: F.F, R: F.D, D: F.L }),
	},
	{
		id: "B-5-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ F: F.F, L: F.U }),
	},
	{
		id: "B-6-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ F: F.F, U: F.R }),
	},
	{
		id: "B-7-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ F: F.F, R: F.D }),
	},
	{
		id: "B-8-C",
		rotation: FundamentalRotations.B,
		scheme: c(pieceIds.FL),
		expectedScheme: m({ F: F.F, D: F.L }),
	},
	{
		id: "B-9-C",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.FLU),
		expectedScheme: m({ F: F.F, U: F.L, R: F.U }),
	},
	{
		id: "B-10-C",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.FRU),
		expectedScheme: m({ F: F.F, R: F.U, D: F.R }),
	},
	{
		id: "B-11-C",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.DFR),
		expectedScheme: m({ F: F.F, L: F.D, D: F.R }),
	},
	{
		id: "B-12-C",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.DFL),
		expectedScheme: m({ F: F.F, L: F.D, U: F.L }),
	},
	{
		id: "B-13-E",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ F: F.F, R: F.U }),
	},
	{
		id: "B-14-E",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ F: F.F, D: F.R }),
	},
	{
		id: "B-15-E",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ F: F.F, L: F.D }),
	},
	{
		id: "B-16-E",
		rotation: FundamentalRotations.B_,
		scheme: c(pieceIds.FL),
		expectedScheme: m({ F: F.F, U: F.L }),
	},
	{
		id: "M-1-E",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.BU),
		expectedScheme: m({ U: F.B, F: F.U }),
	},
	{
		id: "M-3-E",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ F: F.U, D: F.F }),
	},
	{
		id: "M-2-E",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ B: F.D, D: F.F }),
	},
	{
		id: "M-4-E",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.BD),
		expectedScheme: m({ U: F.B, B: F.D }),
	},
	{
		id: "M-5-X",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.U),
		expectedScheme: m({ F: F.U }),
	},
	{
		id: "M-6-X",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.F),
		expectedScheme: m({ D: F.F }),
	},
	{
		id: "M-7-X",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.D),
		expectedScheme: m({ B: F.D }),
	},
	{
		id: "M-8-X",
		rotation: FundamentalRotations.M,
		scheme: c(pieceIds.B),
		expectedScheme: m({ U: F.B }),
	},
	{
		id: "M-9-E",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.BU),
		expectedScheme: m({ B: F.U, D: F.B }),
	},
	{
		id: "M-10-E",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.FU),
		expectedScheme: m({ B: F.U, U: F.F }),
	},
	{
		id: "M-11-E",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.DF),
		expectedScheme: m({ U: F.F, F: F.D }),
	},
	{
		id: "M-12-E",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.BD),
		expectedScheme: m({ F: F.D, D: F.B }),
	},
	{
		id: "M-13-X",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.U),
		expectedScheme: m({ B: F.U }),
	},
	{
		id: "M-14-X",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.F),
		expectedScheme: m({ U: F.F }),
	},
	{
		id: "M-15-X",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.D),
		expectedScheme: m({ F: F.D }),
	},
	{
		id: "M-16-X",
		rotation: FundamentalRotations.M_,
		scheme: c(pieceIds.B),
		expectedScheme: m({ D: F.B }),
	},
	{
		id: "S-1-E",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.LU),
		expectedScheme: m({ U: F.L, R: F.U }),
	},
	{
		id: "S-2-E",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ R: F.U, D: F.R }),
	},
	{
		id: "S-3-E",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ L: F.D, D: F.R }),
	},
	{
		id: "S-4-E",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.DL),
		expectedScheme: m({ L: F.D, U: F.L }),
	},
	{
		id: "S-5-X",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.U),
		expectedScheme: m({ R: F.U }),
	},
	{
		id: "S-6-X",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.R),
		expectedScheme: m({ D: F.R }),
	},
	{
		id: "S-7-X",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.D),
		expectedScheme: m({ L: F.D }),
	},
	{
		id: "S-8-X",
		rotation: FundamentalRotations.S,
		scheme: c(pieceIds.L),
		expectedScheme: m({ U: F.L }),
	},
	{
		id: "S-9-E",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.LU),
		expectedScheme: m({ L: F.U, D: F.L }),
	},
	{
		id: "S-10-E",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.RU),
		expectedScheme: m({ L: F.U, U: F.R }),
	},
	{
		id: "S-11-E",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.DR),
		expectedScheme: m({ U: F.R, R: F.D }),
	},
	{
		id: "S-12-E",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.DL),
		expectedScheme: m({ R: F.D, D: F.L }),
	},
	{
		id: "S-13-X",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.U),
		expectedScheme: m({ L: F.U }),
	},
	{
		id: "S-14-X",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.R),
		expectedScheme: m({ U: F.R }),
	},
	{
		id: "S-15-X",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.D),
		expectedScheme: m({ R: F.D }),
	},
	{
		id: "S-16-X",
		rotation: FundamentalRotations.S_,
		scheme: c(pieceIds.L),
		expectedScheme: m({ D: F.L }),
	},
	{
		id: "E-1-E",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.FL),
		expectedScheme: m({ F: F.L, R: F.F }),
	},
	{
		id: "E-2-E",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ B: F.R, R: F.F }),
	},
	{
		id: "E-3-E",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.BR),
		expectedScheme: m({ L: F.B, B: F.R }),
	},
	{
		id: "E-4-E",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.BL),
		expectedScheme: m({ L: F.B, F: F.L }),
	},
	{
		id: "E-5-X",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.F),
		expectedScheme: m({ R: F.F }),
	},
	{
		id: "E-6-X",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.R),
		expectedScheme: m({ B: F.R }),
	},
	{
		id: "E-7-X",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.B),
		expectedScheme: m({ L: F.B }),
	},
	{
		id: "E-8-X",
		rotation: FundamentalRotations.E,
		scheme: c(pieceIds.L),
		expectedScheme: m({ F: F.L }),
	},
	{
		id: "E-9-E",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.FL),
		expectedScheme: m({ B: F.L, L: F.F }),
	},
	{
		id: "E-10-E",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.FR),
		expectedScheme: m({ L: F.F, F: F.R }),
	},
	{
		id: "E-11-E",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.BR),
		expectedScheme: m({ F: F.R, R: F.B }),
	},
	{
		id: "E-12-E",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.BL),
		expectedScheme: m({ R: F.B, B: F.L }),
	},
	{
		id: "E-13-X",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.F),
		expectedScheme: m({ L: F.F }),
	},
	{
		id: "E-14-X",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.R),
		expectedScheme: m({ F: F.R }),
	},
	{
		id: "E-15-X",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.B),
		expectedScheme: m({ R: F.B }),
	},
	{
		id: "E-16-X",
		rotation: FundamentalRotations.E_,
		scheme: c(pieceIds.L),
		expectedScheme: m({ B: F.L }),
	},
])("$id: Rotation: $rotation | Scheme: $scheme", ({
	rotation,
	scheme,
	expectedScheme,
}: {
	rotation: FundamentalRotations;
	scheme: PieceScheme;
	expectedScheme: PieceScheme;
}) => {
	const rotatedPiece = rotatePiece(rotation, {
		type: PieceType.CORNER,
		scheme,
	});

	expect(rotatedPiece.scheme).toEqual(expectedScheme);
});
